# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Page-Navigation
version:      0.02
version_from: lib/Data/Page/Navigation.pm
installdirs:  site
requires:
    Data::Page:                    2.0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
